"""Stable, dependency-free contracts shared by parking subsystems."""

from parking_rl.core.actions import (
    ZERO_NORMALIZED_ACTION,
    NormalizedAction,
    PhysicalControl,
)
from parking_rl.core.config import ConfigSchemaError, ReferenceConfig, load_reference_config
from parking_rl.core.fingerprint import (
    FingerprintError,
    canonical_data,
    canonical_json_bytes,
    sha256_fingerprint,
)
from parking_rl.core.frames import (
    GoalFrameError,
    GoalRearAxleWorldPose,
    ObjectCentroidWorldPose,
    ObjectEgoFramePose,
    RearAxleWorldPose,
    goal_error_to_rear_axle_world,
    object_ego_to_world,
    object_world_to_ego,
    rear_axle_world_to_goal_error,
    wrap_angle,
)
from parking_rl.core.observation import (
    Observation,
    ObservationField,
    ObservationLayout,
    ObservationRung,
    ObserverConfig,
)
from parking_rl.core.outcomes import (
    EpisodeEndReason,
    EpisodeRuntime,
    StepBoundary,
    resolve_end_reason,
)
from parking_rl.core.scenario import (
    BayDifficulty,
    FrozenScenarioRecord,
    GeneratorProvenance,
    OracleAnnotation,
    OracleSource,
    ParallelDifficulty,
    Scenario,
    TaskFamily,
)
from parking_rl.core.state import (
    ActuatorState,
    Bounds2D,
    EgoState,
    ObjectKind,
    ObjectRole,
    ObjectState,
    SettleProgress,
    StaticWorld,
    VehicleSpec,
    WorldState,
)

__all__ = [
    "ZERO_NORMALIZED_ACTION",
    "ActuatorState",
    "BayDifficulty",
    "Bounds2D",
    "ConfigSchemaError",
    "EgoState",
    "EpisodeEndReason",
    "EpisodeRuntime",
    "FingerprintError",
    "FrozenScenarioRecord",
    "GeneratorProvenance",
    "GoalFrameError",
    "GoalRearAxleWorldPose",
    "NormalizedAction",
    "ObjectCentroidWorldPose",
    "ObjectEgoFramePose",
    "ObjectKind",
    "ObjectRole",
    "ObjectState",
    "Observation",
    "ObservationField",
    "ObservationLayout",
    "ObservationRung",
    "ObserverConfig",
    "OracleAnnotation",
    "OracleSource",
    "ParallelDifficulty",
    "PhysicalControl",
    "RearAxleWorldPose",
    "ReferenceConfig",
    "Scenario",
    "SettleProgress",
    "StaticWorld",
    "StepBoundary",
    "TaskFamily",
    "VehicleSpec",
    "WorldState",
    "canonical_data",
    "canonical_json_bytes",
    "goal_error_to_rear_axle_world",
    "load_reference_config",
    "object_ego_to_world",
    "object_world_to_ego",
    "rear_axle_world_to_goal_error",
    "resolve_end_reason",
    "sha256_fingerprint",
    "wrap_angle",
]
